### ISSUE TITLE
Extend effects resource adapter to show CAP33 effects

### ISSUE THREAD

**Issue by abuiles** [stellar/go#2942]
Depends on https://github.com/stellar/go/issues/2891

**Comment by 2opremio** [comment]
This was fixed in #2951

**Comment by abuiles** [comment]
@2opremio #2951 didn't fix this issue. This issue is about extending protocol and resource adapter to show the effects details in the JSON response. 

It requires adding a struct similar to https://github.com/stellar/go/blob/protocol-14/protocols/horizon/effects/main.go#L230 and then in resourceadapters/effects.go building the correct JSON response.

**Comment by 2opremio** [comment]
It turns out @tamirms was already almost done with this, so I will give way to him instead.

**Comment by abuiles** [comment]
Fixed by @tamirms on #3021
